// LOG OUT
#define COMMAND_REQUEST_LOGOUT							0
#define COMMAND_ON_PLAYER_LOGOUT						1

// RENAME
#define COMMAND_REQUEST_RENAME_PLAYER					2
#define COMMAND_ON_RENAME_PLAYER						3						

// REQUEST PLAYER INFO
#define COMMAND_REQUEST_PLAYER_INFO						4
#define COMMAND_ON_PLAYER_INFO							5

// JOIN TABLE
#define COMMAND_REQUEST_JOIN_TABLE						6
#define COMMAND_ON_PLAYER_JOIN_TABLE					7

// LEAVE TABLE
#define COMMAND_REQUEST_LEAVE_TABLE						8
#define COMMAND_ON_PLAYER_LEAVE_TABLE					9

// READY
#define COMMAND_REQUEST_TO_BE_READY						10
#define COMMAND_ON_PLAYER_READY							11

// SERVE CARDS
#define COMMAND_ON_SERVE_CARDS							12

// BID
#define COMMAND_ON_BID_CHANCE							13
#define COMMAND_REQUEST_TO_BID							14

// SNATCH
#define COMMAND_ON_SNATCH_CHANCE						15
#define COMMAND_REQUEST_TO_SNATCH						16

// LANDLORD SETTLE
#define COMMAND_ON_LANDLORD_SETTLED						17

// LEAD CARD
#define COMMAND_ON_LEAD_CARD							18

// HAND OUT CARDS
#define COMMAND_REQUEST_TO_HAND_OUT_CARDS				19
#define COMMAND_ON_HAND_OUT_CARDS						20

// END
#define COMMAND_ON_ROUND_END							21


